
server:
  port: 8080


spring:
  application:
    name: api-gateway



  cloud:
    gateway:
      routes:

      - id: order-service
        url: http://localhost:8081
        predicates:
          -Path=/order/**

      - id: product-service
        url: http://localhost:8082
        predicates:
          -Path=/product/**



#Rishi singh

# id  Unique Route name
# Url Backend service actual address
# predicates Condition matching gateway incoming request's if match then --> request forward